# Generated by Django 4.1.7 on 2023-04-03 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coffee',
            new_name='Subscriptions',
        ),
    ]
