# Generated by Django 4.1.7 on 2023-05-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_subscriptions_is_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
