# Generated by Django 4.1.7 on 2023-05-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='is_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
