# Generated by Django 4.1.7 on 2023-05-02 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_subscriptions_is_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='is_subscription',
        ),
    ]
